#!/usr/bin/env node
// Generate CATALOG.md: every entry at a glance, in two honest buckets —
//   1. Full checkpoints with a parameter check (estimate vs real weights),
//      sorted worst-deviation-first so the misses are visible, not buried.
//   2. Reference blocks & compact nets with no published weight count to
//      check against (structural reference only).
// The validation claim is only credible if the outliers are shown too.
//
// Usage: node scripts/generate-catalog.mjs   (writes CATALOG.md)
import { readdirSync, existsSync, readFileSync, writeFileSync, statSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const ARCH = join(ROOT, 'architectures');
const RAW = 'https://raw.githubusercontent.com/neurarch-ai/awesome-llm-model-zoo/main/architectures';
const openLink = (id) => `[open](https://www.neurarch.com/?import=${RAW}/${id}/model.json)`;
const grab = (re, s) => { const m = s.match(re); return m ? m[1].trim() : ''; };

const rows = readdirSync(ARCH)
  .filter((d) => statSync(join(ARCH, d)).isDirectory())
  .map((id) => {
    const r = existsSync(join(ARCH, id, 'README.md')) ? readFileSync(join(ARCH, id, 'README.md'), 'utf8') : '';
    const title = grab(/^#\s+(.+)$/m, r) || id;
    const params = grab(/\|\s*Parameters\s*\|\s*([^|]+?)\s*\|/i, r);
    const layers = grab(/\|\s*Layers\s*\|\s*([^|]+?)\s*\|/i, r);
    const type = grab(/\|\s*Type\s*\|\s*([^|]+?)\s*\|/i, r);
    const devStr = grab(/Deviation from the authoritative count \([^)]*\):\s*\*\*([^*]+)\*\*/i, r);
    const dev = devStr ? parseFloat(devStr.replace('%', '')) : null;
    return { id, title, params, layers, type, devStr, dev };
  });

const checked = rows.filter((r) => r.dev !== null).sort((a, b) => Math.abs(b.dev) - Math.abs(a.dev));
const refs = rows.filter((r) => r.dev === null).sort((a, b) => a.title.localeCompare(b.title));
const maxDev = checked.reduce((mx, r) => Math.max(mx, Math.abs(r.dev)), 0);
const within10 = checked.filter((r) => Math.abs(r.dev) <= 10).length;
const secondWorst = Math.abs(checked[1]?.dev ?? 0);

const L = [];
L.push('# Catalog');
L.push('');
L.push(`All ${rows.length} architectures at a glance. Generated by \`scripts/generate-catalog.mjs\` — do not edit by hand.`);
L.push('');
L.push(`## Parameter-checked checkpoints (${checked.length})`);
L.push('');
L.push(`Each carries a **parameter check**: Neurarch's per-layer estimate over the graph vs. the real weight count (Hugging Face safetensors metadata or the official figure). ${within10} of ${checked.length} land within 10%; the next-worst after the top row is ${secondWorst.toFixed(1)}%. The one large outlier is **${checked[0].title} (${checked[0].devStr})** — aggressive weight tying triple-counts a shared embedding, which a per-layer count cannot net out; it is flagged in that entry's README. Sorted worst-first so nothing is hidden.`);
L.push('');
L.push('| Architecture | Params | Layers | Param check | Open |');
L.push('|---|---|---|---|---|');
for (const r of checked) {
  L.push(`| [${r.title}](architectures/${r.id}/) | ${r.params || '—'} | ${r.layers || '—'} | ${r.devStr} | ${openLink(r.id)} |`);
}
L.push('');
L.push(`## Reference blocks & compact nets (${refs.length})`);
L.push('');
L.push('Reference architectures (canonical blocks, recsys models, compact CNN/RNN baselines) with no single published weight count to check an estimate against. Structurally validated like every other entry; open one to see and edit the full graph.');
L.push('');
L.push('| Architecture | Type | Open |');
L.push('|---|---|---|');
for (const r of refs) {
  L.push(`| [${r.title}](architectures/${r.id}/) | ${r.type || '—'} | ${openLink(r.id)} |`);
}
L.push('');

writeFileSync(join(ROOT, 'CATALOG.md'), L.join('\n'));
console.log(`Wrote CATALOG.md — ${checked.length} param-checked (within 10%: ${within10}, max ${maxDev.toFixed(1)}%), ${refs.length} reference entries`);
