/**
 * Model-zoo generator (maintainers only).
 *
 * Builds every architecture entry (model.json + assets/diagram.svg + README.md)
 * from verified specs, using the Neurarch source checkout expected at a
 * sibling directory (../Neurarch). Run from the zoo repo root:
 *
 *   npx tsx --tsconfig ../Neurarch/tsconfig.json scripts/generate.mts
 *
 * Entry sources:
 *  - decoder/encoder specs: hand-verified against the official config.json on HF
 *  - template entries: copied from Neurarch's in-app template library
 *  - parser entries: generated by Neurarch's paper-architecture parser
 *
 * Every graph is validated with Neurarch's own shape propagator before it is
 * written; the script fails loudly on any shape error.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const NEURARCH = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../Neurarch');
const ZOO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

const { exportPaperSvg } = await import(path.join(NEURARCH, 'src/utils/figureExporter.ts'));
const { propagateShapes } = await import(path.join(NEURARCH, 'src/utils/shapeInference.ts'));
const { parsePaperTextToModel } = await import(path.join(NEURARCH, 'src/utils/paperArchitectureParser.ts'));

// ---------------------------------------------------------------------------
// Spec types
// ---------------------------------------------------------------------------

type Link = [label: string, url: string];

interface DecoderSpec {
  kind: 'decoder';
  id: string; displayName: string; org: string; paramsLabel: string;
  github: string; hf: string; license: string;
  hidden: number; layers: number; heads: number; kvHeads: number;
  ffn: number; vocab: number; ctx: number; ropeDim: number;
  notes: string[]; blurb: string;
}

interface EncoderSpec {
  kind: 'encoder';
  id: string; displayName: string; org: string; paramsLabel: string;
  github: string; hf: string; license: string;
  hidden: number; layers: number; heads: number; ffn: number;
  vocab: number; maxPos: number;
  notes: string[]; blurb: string;
}

interface TemplateEntry {
  kind: 'template';
  tid: string; // folder under Neurarch public/templates
  id: string;  // zoo folder id
  displayName: string; org: string; paramsLabel: string;
  links: Link[]; license?: string;
  blurb: string; notes: string[];
  patch?: (model: { components: Array<{ name: string; params: Record<string, unknown> }> }) => void;
}

interface ParserEntry {
  kind: 'parser';
  parseName: string; // name fed to parsePaperTextToModel
  id: string; displayName: string; org: string; paramsLabel: string;
  links: Link[]; license?: string;
  blurb: string; notes: string[];
}

type Spec = DecoderSpec | EncoderSpec | TemplateEntry | ParserEntry;

// ---------------------------------------------------------------------------
// Decoder-only LLMs (config.json-verified)
// ---------------------------------------------------------------------------

const DECODERS: DecoderSpec[] = [
  {
    kind: 'decoder', id: 'qwen2.5-7b', displayName: 'Qwen2.5-7B', org: 'Alibaba Cloud (Qwen team)',
    paramsLabel: '7.6B', github: 'https://github.com/QwenLM/Qwen2.5', hf: 'https://huggingface.co/Qwen/Qwen2.5-7B',
    license: 'Apache 2.0',
    hidden: 3584, layers: 28, heads: 28, kvHeads: 4, ffn: 18944, vocab: 152064, ctx: 131072, ropeDim: 128,
    notes: [
      'Grouped-query attention with 28 query heads sharing 4 KV heads (7:1 ratio), which keeps the KV cache small at long context.',
      'Unusually for the Llama lineage, Qwen adds a bias term to the Q, K, V projections (attention bias on, everywhere else off).',
      'Wide FFN: the SwiGLU intermediate size (18944) is about 5.3x the hidden size, wider than the Llama-2 ratio.',
      'Native 131072-token context window with rope_theta = 1e6.',
    ],
    blurb: 'A 7.6B-parameter decoder-only transformer from the Qwen2.5 family, one of the most widely deployed open-weight Chinese and multilingual LLM series. Llama-style pre-norm decoder with grouped-query attention, RoPE, RMSNorm, and SwiGLU.',
  },
  {
    kind: 'decoder', id: 'deepseek-llm-7b', displayName: 'DeepSeek-LLM-7B', org: 'DeepSeek',
    paramsLabel: '7B', github: 'https://github.com/deepseek-ai/DeepSeek-LLM', hf: 'https://huggingface.co/deepseek-ai/deepseek-llm-7b-base',
    license: 'Code MIT; weights under the DeepSeek Model License (commercial use permitted)',
    hidden: 4096, layers: 30, heads: 32, kvHeads: 32, ffn: 11008, vocab: 102400, ctx: 4096, ropeDim: 128,
    notes: [
      'The dense ancestor of the DeepSeek series, before the MoE turn (V2/V3). Architecture is deliberately Llama-compatible: model_type in config.json is literally "llama".',
      'Plain multi-head attention at 7B (32 Q = 32 KV heads); only the 67B sibling adopted grouped-query attention.',
      '30 layers instead of the usual 32, slightly shallower and wider than Llama-2-7B.',
      'Large 102400-token byte-level BPE vocabulary tuned for bilingual Chinese and English text.',
    ],
    blurb: 'The original dense 7B model from DeepSeek, trained on 2T bilingual tokens. A clean Llama-style decoder (RoPE, RMSNorm, SwiGLU) with a large bilingual vocabulary, and the architectural starting point of the DeepSeek lineage.',
  },
  {
    kind: 'decoder', id: 'chatglm3-6b', displayName: 'ChatGLM3-6B', org: 'Zhipu AI / Tsinghua KEG (THUDM)',
    paramsLabel: '6.2B', github: 'https://github.com/THUDM/ChatGLM3', hf: 'https://huggingface.co/THUDM/chatglm3-6b',
    license: 'Code Apache 2.0; weights under the ChatGLM3-6B license (free commercial use after registration)',
    hidden: 4096, layers: 28, heads: 32, kvHeads: 2, ffn: 13696, vocab: 65024, ctx: 8192, ropeDim: 64,
    notes: [
      'Aggressive multi-query-style attention: 32 query heads share only 2 KV groups (multi_query_group_num = 2), a 16:1 ratio that shrinks the KV cache far more than typical GQA.',
      'GLM-style partial RoPE: rotary embedding is applied to half of each 128-dim head (rotary dim 64); the other half stays position-free.',
      'The FFN intermediate size (13696) follows the GLM recipe rather than the Llama 8/3 ratio.',
      '8192-token base context; -32k and -128k long-context variants exist.',
    ],
    blurb: 'The third generation of the ChatGLM series from Zhipu AI and Tsinghua, historically the most-starred Chinese open LLM. A pre-norm decoder with extreme grouped (near-multi-query) attention and GLM-style partial rotary embeddings.',
  },
  {
    kind: 'decoder', id: 'baichuan2-7b', displayName: 'Baichuan2-7B', org: 'Baichuan Inc.',
    paramsLabel: '7B', github: 'https://github.com/baichuan-inc/Baichuan2', hf: 'https://huggingface.co/baichuan-inc/Baichuan2-7B-Base',
    license: 'Code Apache 2.0; weights under the Baichuan2 Community License (free commercial use after application)',
    hidden: 4096, layers: 32, heads: 32, kvHeads: 32, ffn: 11008, vocab: 125696, ctx: 4096, ropeDim: 128,
    notes: [
      'Llama-2-7B shape (32 layers, 4096 hidden, 11008 FFN) with a much larger 125696-token vocabulary optimized for Chinese.',
      'NormHead: the output embedding (LM head) rows are L2-normalized before the logit matmul, which the tech report credits with stabilizing training.',
      'The 7B model uses RoPE; do not confuse it with the 13B sibling, which uses ALiBi instead.',
      'Trained on 2.6T tokens; one of the first Chinese LLMs to ship intermediate training checkpoints for research.',
    ],
    blurb: 'Baichuan Inc.\'s second-generation 7B base model, a Llama-shaped pre-norm decoder distinguished by a large Chinese-optimized vocabulary and a normalized output head (NormHead).',
  },
  {
    kind: 'decoder', id: 'yi-6b', displayName: 'Yi-6B', org: '01.AI',
    paramsLabel: '6B', github: 'https://github.com/01-ai/Yi', hf: 'https://huggingface.co/01-ai/Yi-6B',
    license: 'Apache 2.0 (relicensed from the Yi License in 2024)',
    hidden: 4096, layers: 32, heads: 32, kvHeads: 4, ffn: 11008, vocab: 64000, ctx: 4096, ropeDim: 128,
    notes: [
      'Fully Llama-compatible architecture (model_type "llama"), so the whole Llama tooling ecosystem works out of the box.',
      'Grouped-query attention even at 6B scale: 32 query heads over 4 KV heads, unusual for a model this small at the time.',
      'High rope_theta (5e6) chosen with long-context extension in mind; the Yi-6B-200K variant stretches the same architecture to 200k tokens.',
      'Compact 64000-token bilingual vocabulary.',
    ],
    blurb: 'The 6B base model from 01.AI (founded by Kai-Fu Lee), trained on 3.1T bilingual tokens. A Llama-style decoder notable for using grouped-query attention at small scale and for its 200K long-context variant.',
  },
  {
    kind: 'decoder', id: 'internlm2-7b', displayName: 'InternLM2-7B', org: 'Shanghai AI Laboratory',
    paramsLabel: '7.7B', github: 'https://github.com/InternLM/InternLM', hf: 'https://huggingface.co/internlm/internlm2-7b',
    license: 'Code Apache 2.0; weights free for commercial use after application',
    hidden: 4096, layers: 32, heads: 32, kvHeads: 8, ffn: 14336, vocab: 92544, ctx: 32768, ropeDim: 128,
    notes: [
      'Llama-3-like shape a year early: 32 layers, GQA 32:8, and the same 14336 FFN intermediate size.',
      'Native 32768-token context trained with rope_theta = 1e6, extrapolating to 200k in the chat variants.',
      'Consolidated W_qkv weight layout: q, k, v are stored interleaved per KV group, which matters when converting checkpoints.',
      '92544-token vocabulary covering Chinese, English, and code.',
    ],
    blurb: 'Shanghai AI Laboratory\'s second-generation 7B base model. A pre-norm decoder with 32:8 grouped-query attention and a native 32k context window, plus strong tool-use and long-context chat variants.',
  },
  {
    kind: 'decoder', id: 'minicpm-2b', displayName: 'MiniCPM-2B', org: 'ModelBest / OpenBMB (Tsinghua NLP)',
    paramsLabel: '2.4B (non-embedding)', github: 'https://github.com/OpenBMB/MiniCPM', hf: 'https://huggingface.co/openbmb/MiniCPM-2B-sft-bf16',
    license: 'Apache 2.0 (code); weights free for commercial use after registration',
    hidden: 2304, layers: 40, heads: 36, kvHeads: 36, ffn: 5760, vocab: 122753, ctx: 4096, ropeDim: 64,
    notes: [
      'Deep-and-thin: 40 layers at only 2304 hidden, the opposite trade-off from most 2B-class models.',
      'muP-style stability tricks baked into the architecture: embedding output scaled by scale_emb = 12, residual branches scaled by scale_depth / sqrt(num_layers), and tied input/output embeddings.',
      'Plain multi-head attention (36 heads, 64-dim each); the KV-cache saving tricks were left out at this scale.',
      'A 122753-token vocabulary, very large for a 2B model, reflecting its Chinese-first design.',
    ],
    blurb: 'OpenBMB\'s flagship small LLM, a 2.4B deep-and-thin decoder that punches above its weight via muP-style scaling (scale_emb, scaled residuals, tied embeddings) found by extensive scaling-law sweeps.',
  },
  {
    kind: 'decoder', id: 'skywork-13b', displayName: 'Skywork-13B', org: 'Kunlun Tech (SkyworkAI)',
    paramsLabel: '13B', github: 'https://github.com/SkyworkAI/Skywork', hf: 'https://huggingface.co/Skywork/Skywork-13B-base',
    license: 'Code Apache-style; weights under the Skywork Community License (free commercial use after agreement)',
    hidden: 4608, layers: 52, heads: 36, kvHeads: 36, ffn: 12288, vocab: 65519, ctx: 4096, ropeDim: 128,
    notes: [
      'Deliberately deep-and-thin at 13B scale: 52 layers at 4608 hidden, versus Llama-2-13B\'s 40 layers at 5120. The tech report (arXiv 2310.19341) ablates this choice directly.',
      'Plain multi-head attention (36 heads), RoPE, RMSNorm, SwiGLU; the FFN ratio is a modest 2.67x.',
      '65519-token vocabulary balanced for Chinese and English; trained on 3.2T tokens.',
      'Ships with a clean tech report and intermediate checkpoints, making it a good reference for training-dynamics work.',
    ],
    blurb: 'Kunlun Tech\'s 13B bilingual base model, notable for an explicitly ablated deep-and-thin layout (52 layers) and a thorough public tech report on its 3.2T-token training run.',
  },
  {
    kind: 'decoder', id: 'llama3-8b', displayName: 'Llama-3-8B', org: 'Meta',
    paramsLabel: '8B', github: 'https://github.com/meta-llama/llama3', hf: 'https://huggingface.co/meta-llama/Meta-Llama-3-8B',
    license: 'Llama 3 Community License',
    hidden: 4096, layers: 32, heads: 32, kvHeads: 8, ffn: 14336, vocab: 128256, ctx: 8192, ropeDim: 128,
    notes: [
      'The reference open-weight architecture of 2024: 32 layers, GQA 32:8, SwiGLU 14336, RMSNorm pre-norm. Half the models in this zoo are best described as deltas against this graph.',
      'Big vocabulary jump over Llama-2: 128256 tokens (tiktoken-style BPE), which moves a meaningful fraction of parameters into the embedding and head.',
      'rope_theta raised to 500000 for the native 8192-token context.',
      'Grouped-query attention arrived at the 8B scale here; Llama-2-7B was still plain MHA.',
    ],
    blurb: 'Meta\'s 8B dense decoder, the de facto baseline architecture that most current open LLMs (including many in this zoo) derive from or compare against.',
  },
  {
    kind: 'decoder', id: 'mistral-7b', displayName: 'Mistral-7B', org: 'Mistral AI',
    paramsLabel: '7.2B', github: 'https://github.com/mistralai/mistral-inference', hf: 'https://huggingface.co/mistralai/Mistral-7B-v0.1',
    license: 'Apache 2.0',
    hidden: 4096, layers: 32, heads: 32, kvHeads: 8, ffn: 14336, vocab: 32000, ctx: 32768, ropeDim: 128,
    notes: [
      'Sliding-window attention: each layer attends to the previous 4096 tokens only; stacking 32 layers grows the effective receptive field to the full 32768-token context. The graph shows standard GQA; the window is an attention-mask detail.',
      'Grouped-query attention 32:8 plus the sliding window made it the fastest-inference 7B of its generation.',
      'Kept the compact Llama-2 32000-token vocabulary while adopting the larger 14336 FFN.',
      'The dense base that Mixtral 8x7B sparsified: the MoE model reuses this exact block with the FFN swapped for 8 experts.',
    ],
    blurb: 'The 7B model from Mistral AI that beat Llama-2-13B at release, built on grouped-query attention plus sliding-window attention. The direct dense ancestor of Mixtral.',
  },
];

// ---------------------------------------------------------------------------
// BERT-family encoders (config.json-verified)
// ---------------------------------------------------------------------------

const ENCODERS: EncoderSpec[] = [
  {
    kind: 'encoder', id: 'chinese-roberta-wwm-ext', displayName: 'Chinese-RoBERTa-wwm-ext', org: 'HFL (HIT and iFLYTEK joint lab)',
    paramsLabel: '102M', github: 'https://github.com/ymcui/Chinese-BERT-wwm', hf: 'https://huggingface.co/hfl/chinese-roberta-wwm-ext',
    license: 'Apache 2.0',
    hidden: 768, layers: 12, heads: 12, ffn: 3072, vocab: 21128, maxPos: 512,
    notes: [
      'Despite the RoBERTa name, this is architecturally BERT-base: it loads as BertModel with absolute learned positions and post-layer-norm. "RoBERTa" refers to the training recipe (no NSP, dynamic masking), not the architecture.',
      'Whole-word masking (wwm) masks all WordPiece pieces of a Chinese word together, which matters because Chinese has no whitespace word boundaries.',
      '21128-token Chinese WordPiece vocabulary, the de facto standard for Chinese BERT-family checkpoints.',
      'For a decade of Chinese NLU benchmarks (CLUE, etc.), this checkpoint was the baseline everyone compared against.',
    ],
    blurb: 'The standard Chinese encoder from HFL: BERT-base architecture trained RoBERTa-style with whole-word masking on extended data. Still the default starting point for Chinese classification, NER, and retrieval fine-tuning.',
  },
  {
    kind: 'encoder', id: 'ernie-3.0-base-zh', displayName: 'ERNIE 3.0 Base (Chinese)', org: 'Baidu',
    paramsLabel: '118M', github: 'https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-3.0', hf: 'https://huggingface.co/nghuyong/ernie-3.0-base-zh',
    license: 'Apache 2.0 (PaddleNLP)',
    hidden: 768, layers: 12, heads: 12, ffn: 3072, vocab: 40000, maxPos: 2048,
    notes: [
      'BERT-base shape with two ERNIE twists: a 40000-token vocabulary (almost 2x BERT\'s Chinese vocab) and a 2048 max position, four times BERT\'s 512.',
      'Adds a task-type embedding alongside token and position embeddings, a remnant of ERNIE 3.0\'s multi-task universal-representation pretraining.',
      'Distilled from the 10B ERNIE 3.0 Titan teacher; the base model is what ships for practical NLU.',
      'Official weights are Paddle-native; the linked HF checkpoint is the standard PyTorch conversion by nghuyong.',
    ],
    blurb: 'Baidu\'s workhorse Chinese encoder, the base-size distillation of the ERNIE 3.0 family. BERT-base shape with a larger vocabulary, 2048-token positions, and knowledge-enhanced pretraining.',
  },
  {
    kind: 'encoder', id: 'bert-base', displayName: 'BERT-Base', org: 'Google',
    paramsLabel: '110M', github: 'https://github.com/google-research/bert', hf: 'https://huggingface.co/google-bert/bert-base-uncased',
    license: 'Apache 2.0',
    hidden: 768, layers: 12, heads: 12, ffn: 3072, vocab: 30522, maxPos: 512,
    notes: [
      'The model that made pretrain-then-finetune the default workflow in NLP (Devlin et al. 2018, arXiv 1810.04805).',
      'Post-norm placement: LayerNorm comes after each residual add, the original Transformer ordering that pre-norm models later abandoned for training stability.',
      'Learned absolute position embeddings hard-cap the context at 512 tokens.',
      '30522-token WordPiece vocabulary; masked-language-modeling plus next-sentence-prediction pretraining.',
    ],
    blurb: 'The bidirectional encoder that started the transfer-learning era in NLP. Twelve post-norm encoder blocks, 768 hidden, 12 heads: the shape every "base-size" encoder since has copied.',
  },
];

// ---------------------------------------------------------------------------
// Entries copied from Neurarch's in-app template library
// ---------------------------------------------------------------------------

const TEMPLATES: TemplateEntry[] = [
  {
    kind: 'template', tid: 'llama3-block', id: 'llama3-block', displayName: 'Llama-3 Decoder Block', org: 'Meta',
    paramsLabel: 'Block graph (8B dims)',
    links: [
      ['Paper (Llama 3 Herd of Models, 2024)', 'https://arxiv.org/abs/2407.21783'],
      ['GitHub', 'https://github.com/meta-llama/llama3'],
      ['Hugging Face', 'https://huggingface.co/meta-llama/Meta-Llama-3-8B'],
    ],
    blurb: 'A single Llama-3 decoder block at 8B dimensions, expanded to individual operations: RMSNorm, grouped-query attention with RoPE, residual add, RMSNorm, SwiGLU FFN, residual add. The companion to the full [llama3-8b](../llama3-8b/) entry.',
    notes: [
      'Shows the block internals that the full-model entry collapses: both residual streams, the pre-norm placement, and RoPE feeding the attention node.',
      'GQA 32 query heads over 8 KV heads; SwiGLU intermediate size 14336.',
      'Useful as a starting graph when you want to modify the block itself (try MoE, different norms, attention variants) and re-validate.',
    ],
    patch: (m) => {
      const swiglu = m.components.find((c) => c.name === 'swiglu_ffn');
      if (swiglu) swiglu.params.intermediateSize = 14336; // app template still has the Llama-2 11008
    },
  },
  {
    kind: 'template', tid: 'mixtral-block', id: 'mixtral-block', displayName: 'Mixtral MoE Block', org: 'Mistral AI',
    paramsLabel: 'Block graph',
    links: [
      ['Paper (Jiang et al. 2024)', 'https://arxiv.org/abs/2401.04088'],
      ['Hugging Face', 'https://huggingface.co/mistralai/Mixtral-8x7B-v0.1'],
    ],
    blurb: 'The Mixtral 8x7B decoder block: the Mistral-7B block with its dense FFN swapped for a sparse mixture of 8 expert FFNs, top-2 routed per token.',
    notes: [
      'Sparse MoE layer: 8 experts, top-2 routing, so roughly 13B of 47B total parameters are active per token.',
      'Everything around the MoE layer is the Mistral-7B recipe: GQA 32:8 with RoPE, RMSNorm pre-norm, dual residual streams.',
      'The canonical open-weight example of decoupling parameter count from inference FLOPs.',
    ],
  },
  {
    kind: 'template', tid: 'mamba-block', id: 'mamba-block', displayName: 'Mamba SSM Block', org: 'CMU / Princeton (Gu and Dao)',
    paramsLabel: 'Block graph',
    links: [
      ['Paper (Gu and Dao 2023)', 'https://arxiv.org/abs/2312.00752'],
      ['GitHub', 'https://github.com/state-spaces/mamba'],
    ],
    blurb: 'The Mamba selective state-space block: causal conv plus gated selective SSM in place of attention, giving linear-time sequence mixing with no KV cache.',
    notes: [
      'No attention anywhere: the selective SSM scan does the sequence mixing in O(T) time and O(1) inference state.',
      'The gating path (SiLU-gated multiply) and the input-dependent SSM parameters are what "selective" refers to.',
      'The strongest attention-free architecture family; hybrids (Jamba, Zamba) interleave this block with attention.',
    ],
  },
  {
    kind: 'template', tid: 'phi3-mini', id: 'phi3-mini', displayName: 'Phi-3 Mini Block', org: 'Microsoft',
    paramsLabel: 'Block graph (3.8B dims)',
    links: [
      ['Paper (Abdin et al. 2024)', 'https://arxiv.org/abs/2404.14219'],
      ['Hugging Face', 'https://huggingface.co/microsoft/Phi-3-mini-4k-instruct'],
    ],
    blurb: 'The Phi-3 Mini (3.8B) decoder block: a compact Llama-style block at 3072 hidden, the architecture behind the "small model trained on textbook-quality data" line of work.',
    notes: [
      'Full multi-head attention (32 heads at 3072, head dim 96); no GQA at this scale in the 4k variant.',
      'SwiGLU FFN at 8192 intermediate, RMSNorm pre-norm, RoPE.',
      'Architecturally conventional on purpose: the Phi thesis is that data quality, not architecture novelty, drives small-model performance.',
    ],
  },
  {
    kind: 'template', tid: 'transformer-block', id: 'transformer-block', displayName: 'Transformer Encoder Block', org: 'Google (Vaswani et al.)',
    paramsLabel: 'Block graph',
    links: [
      ['Paper (Vaswani et al. 2017)', 'https://arxiv.org/abs/1706.03762'],
    ],
    blurb: 'The original "Attention Is All You Need" encoder block: multi-head self-attention and a position-wise FFN, each wrapped in residual + post-LayerNorm.',
    notes: [
      'Post-norm ordering as published in 2017; nearly every modern descendant flipped to pre-norm for training stability.',
      'The minimal pedagogical graph: 8 nodes, two residual streams, nothing else.',
      'Fork point for trying attention or norm variants with instant shape re-validation.',
    ],
  },
  {
    kind: 'template', tid: 't5-small', id: 't5-small', displayName: 'T5-Small', org: 'Google',
    paramsLabel: '60M',
    links: [
      ['Paper (Raffel et al. 2019)', 'https://arxiv.org/abs/1910.10683'],
      ['Hugging Face', 'https://huggingface.co/google-t5/t5-small'],
    ],
    license: 'Apache 2.0',
    blurb: 'The text-to-text encoder-decoder that reframed every NLP task as sequence generation. This graph shows the full two-stream layout: bidirectional encoder, causal decoder, and cross-attention tying them together.',
    notes: [
      'Both streams share one 32128-token SentencePiece embedding matrix.',
      'RMSNorm (T5 called it "simplified LayerNorm") years before the Llama lineage made it standard; relative position biases instead of absolute embeddings.',
      'The graph makes the three attention types visually distinct: encoder self-attention, decoder causal self-attention, and cross-attention.',
    ],
  },
  {
    kind: 'template', tid: 'simple-rnn', id: 'simple-rnn', displayName: 'Simple RNN', org: 'Educational (Elman 1990)',
    paramsLabel: 'Starter graph',
    links: [
      ['Paper (Elman 1990, Finding Structure in Time)', 'https://onlinelibrary.wiley.com/doi/10.1207/s15516709cog1402_1'],
    ],
    blurb: 'A minimal Elman-style recurrent network for sequence processing. Four nodes: the smallest sequential model in the zoo, kept as a teaching baseline.',
    notes: [
      'The architecture every LSTM, GRU, and ultimately attention mechanism was reacting to.',
      'Useful as a first graph for learning the canvas: add layers, watch shapes propagate.',
    ],
  },
  {
    kind: 'template', tid: 'vit-b16', id: 'vit-b16', displayName: 'ViT-B/16', org: 'Google',
    paramsLabel: '86M',
    links: [
      ['Paper (Dosovitskiy et al. 2020)', 'https://arxiv.org/abs/2010.11929'],
      ['Hugging Face', 'https://huggingface.co/google/vit-base-patch16-224'],
    ],
    license: 'Apache 2.0',
    blurb: 'The Vision Transformer that ended CNN hegemony in image classification: 16x16 patch embedding, learned position embeddings, and a stack of standard pre-norm Transformer encoder blocks.',
    notes: [
      'The patch-embed stem is just a strided conv: 3x224x224 becomes 196 patch tokens of 768 dims (plus the class token).',
      'One of the 12 identical encoder blocks is expanded (MHA 12 heads, MLP 3072, pre-norm, both residuals); the stack repeats x12.',
      'Identical block to BERT but pre-norm; the inductive-bias-free design needs large-scale pretraining to win.',
    ],
  },
  {
    kind: 'template', tid: 'resnet-block', id: 'resnet-block', displayName: 'ResNet Residual Block', org: 'Microsoft Research (He et al.)',
    paramsLabel: 'Block graph',
    links: [
      ['Paper (He et al. 2015)', 'https://arxiv.org/abs/1512.03385'],
    ],
    blurb: 'The residual unit from ResNet: conv-BN-ReLU twice, plus the identity skip connection that made 100+ layer networks trainable. Arguably the most influential 9 nodes in deep learning.',
    notes: [
      'The skip connection turns layers into residual functions; every modern transformer residual stream descends from this idea.',
      'Companion to the full [resnet-50](../resnet-50/) entry, which stacks bottleneck versions of this block 16 times.',
    ],
  },
  {
    kind: 'template', tid: 'simple-cnn', id: 'simple-cnn', displayName: 'Simple CNN', org: 'Educational (LeCun lineage)',
    paramsLabel: 'Starter graph',
    links: [
      ['Paper (LeCun et al. 1998, LeNet)', 'https://ieeexplore.ieee.org/document/726791'],
    ],
    blurb: 'A LeNet-style starter CNN for image classification: conv-pool stacks into a dense head. The "hello world" graph of computer vision.',
    notes: [
      'The pattern (convolution for local features, pooling for downsampling, dense layers for classification) is unchanged since 1998.',
      'Good first graph for watching shape propagation catch kernel/stride mistakes.',
    ],
  },
  {
    kind: 'template', tid: 'unet', id: 'unet', displayName: 'U-Net', org: 'University of Freiburg (Ronneberger et al.)',
    paramsLabel: '31M (original)',
    links: [
      ['Paper (Ronneberger et al. 2015)', 'https://arxiv.org/abs/1505.04597'],
    ],
    blurb: 'The encoder-decoder with skip connections that owns biomedical and dense-prediction segmentation. Contracting path captures context, expanding path recovers resolution, skips carry the detail across.',
    notes: [
      'The long skip connections (encoder level i concatenated into decoder level i) are the defining feature; without them the decoder cannot localize.',
      'Still the backbone shape of choice ten years on, including inside latent diffusion models (see [diffusion-unet](../diffusion-unet/)).',
    ],
  },
  {
    kind: 'template', tid: 'diffusion-unet', id: 'diffusion-unet', displayName: 'Diffusion U-Net (Stable Diffusion)', org: 'CompVis / Stability AI',
    paramsLabel: '~860M (SD 1.x UNet)',
    links: [
      ['Paper (Rombach et al. 2022)', 'https://arxiv.org/abs/2112.10752'],
      ['GitHub', 'https://github.com/CompVis/stable-diffusion'],
      ['Hugging Face', 'https://huggingface.co/CompVis/stable-diffusion-v1-4'],
    ],
    license: 'CreativeML OpenRAIL-M (SD 1.x weights)',
    blurb: 'The latent-diffusion noise predictor behind Stable Diffusion: a U-Net operating on 64x64 latents, conditioned on the timestep and on text embeddings via cross-attention at every resolution.',
    notes: [
      'Cross-attention is the text-conditioning mechanism: image latents attend to CLIP text embeddings inside each block.',
      'Works in 4x64x64 VAE latent space rather than pixels, which is the "latent" in latent diffusion and why it fits on consumer GPUs.',
      'Timestep embedding is injected alongside the latents so one network handles every noise level.',
    ],
  },
  {
    kind: 'template', tid: 'whisper-small', id: 'whisper-small', displayName: 'Whisper Small', org: 'OpenAI',
    paramsLabel: '244M',
    links: [
      ['Paper (Radford et al. 2022)', 'https://arxiv.org/abs/2212.04356'],
      ['GitHub', 'https://github.com/openai/whisper'],
      ['Hugging Face', 'https://huggingface.co/openai/whisper-small'],
    ],
    license: 'MIT',
    blurb: 'OpenAI\'s speech recognition encoder-decoder: log-mel spectrogram through a two-layer conv stem into a Transformer encoder, with a causal text decoder cross-attending to the audio states.',
    notes: [
      'The conv stem (two 1D convs with GeLU) downsamples the 80-channel mel input 2x before the encoder; everything after is a vanilla Transformer.',
      'Trained on 680k hours of weakly supervised audio; the architecture is intentionally boring so the data does the work.',
      'The graph shows both streams plus cross-attention, the same enc-dec wiring as T5 with an audio front-end.',
    ],
  },
  {
    kind: 'template', tid: 'two-tower', id: 'two-tower', displayName: 'Two-Tower Retrieval', org: 'Google (YouTube) lineage',
    paramsLabel: 'Reference graph',
    links: [
      ['Paper (Covington et al. 2016)', 'https://dl.acm.org/doi/10.1145/2959100.2959190'],
      ['Paper (Yi et al. 2019, sampling-bias-corrected)', 'https://dl.acm.org/doi/10.1145/3298689.3346996'],
    ],
    blurb: 'The dual-encoder retrieval architecture behind virtually every industrial recommender and semantic search stack: user tower and item tower embed into the same space, scored by dot product.',
    notes: [
      'The towers never interact until the final dot product, which is what makes billion-item retrieval feasible (items pre-embedded into an ANN index).',
      'Each tower here is embeddings into an MLP; in production the towers grow but the contract (two encoders, one similarity) stays.',
    ],
  },
  {
    kind: 'template', tid: 'wide-and-deep', id: 'wide-and-deep', displayName: 'Wide & Deep', org: 'Google',
    paramsLabel: 'Reference graph',
    links: [
      ['Paper (Cheng et al. 2016)', 'https://arxiv.org/abs/1606.07792'],
    ],
    blurb: 'Google\'s Play-store ranking model that joint-trains a wide linear path (memorization of cross features) with a deep embedding MLP (generalization), summed at the logit.',
    notes: [
      'The wide path memorizes specific feature crosses; the deep path generalizes to unseen ones; the sum gets both behaviors in one model.',
      'The conceptual ancestor of DeepFM, DCN, and most hybrid CTR architectures since.',
    ],
  },
  {
    kind: 'template', tid: 'dlrm', id: 'dlrm', displayName: 'DLRM', org: 'Meta',
    paramsLabel: 'Reference graph',
    links: [
      ['Paper (Naumov et al. 2019)', 'https://arxiv.org/abs/1906.00091'],
      ['GitHub', 'https://github.com/facebookresearch/dlrm'],
    ],
    blurb: 'Meta\'s production recommendation architecture: a bottom MLP for dense features, embedding tables for sparse features, explicit pairwise dot-product interactions, and a top MLP over the result.',
    notes: [
      'The explicit pairwise interaction layer (dot products between all embedding pairs) is the signature; it is factorization machines absorbed into a deep net.',
      'At production scale the embedding tables dominate parameters so heavily that DLRM training is a memory-bandwidth problem, which shaped a generation of recsys hardware.',
    ],
  },
  {
    kind: 'template', tid: 'ncf', id: 'ncf', displayName: 'NCF (concat-MLP)', org: 'NUS (He et al.)',
    paramsLabel: 'Reference graph',
    links: [
      ['Paper (He et al. 2017)', 'https://arxiv.org/abs/1708.05031'],
      ['GitHub', 'https://github.com/hexiangnan/neural_collaborative_filtering'],
    ],
    blurb: 'Neural Collaborative Filtering in its simplest form: user and item embeddings concatenated into an MLP that learns the interaction function instead of assuming a dot product.',
    notes: [
      'The pure-MLP variant of the NCF paper; the fused GMF+MLP variant is the separate [neumf](../neumf/) entry.',
      'The paper\'s claim that an MLP beats the inner product sparked a years-long replication debate (Rendle et al. 2020); keep both graphs around to test it yourself.',
    ],
  },
  {
    kind: 'template', tid: 'neumf', id: 'neumf', displayName: 'NeuMF (GMF + MLP)', org: 'NUS (He et al.)',
    paramsLabel: 'Reference graph',
    links: [
      ['Paper (He et al. 2017)', 'https://arxiv.org/abs/1708.05031'],
      ['GitHub', 'https://github.com/hexiangnan/neural_collaborative_filtering'],
    ],
    blurb: 'The full NCF model: a Generalized Matrix Factorization path (element-wise product of embeddings) fused with an MLP path, each with its own embedding tables, joined before the final score.',
    notes: [
      'Two separate embedding sets, one per path, concatenated at the last layer: the structural detail most reimplementations get wrong.',
      'GMF preserves the classic MF inductive bias while the MLP path adds flexibility; the fusion is the paper\'s actual headline model.',
    ],
  },
  {
    kind: 'template', tid: 'lightgcn', id: 'lightgcn', displayName: 'LightGCN', org: 'USTC / NUS (He et al.)',
    paramsLabel: 'Reference graph',
    links: [
      ['Paper (He et al. 2020)', 'https://arxiv.org/abs/2002.02126'],
      ['GitHub', 'https://github.com/gusye1234/LightGCN-PyTorch'],
    ],
    blurb: 'Graph convolution for collaborative filtering stripped to its minimum: no feature transforms, no nonlinearities, just neighborhood propagation over the user-item graph and a layer-wise average.',
    notes: [
      'An ablation result turned architecture: removing the transforms and activations from NGCF improved accuracy.',
      'Final embeddings average over propagation layers (layer combination), capturing multi-hop signals at different ranges.',
    ],
  },
  {
    kind: 'template', tid: 'graph-sage-rec', id: 'graph-sage-rec', displayName: 'GraphSAGE Recommender', org: 'Stanford (Hamilton et al.)',
    paramsLabel: 'Reference graph',
    links: [
      ['Paper (Hamilton et al. 2017)', 'https://arxiv.org/abs/1706.02216'],
    ],
    blurb: 'Inductive node embeddings by sampling and aggregating neighborhoods, wired here as a recommendation retrieval encoder. The architecture PinSage scaled to billions of pins.',
    notes: [
      'Inductive, not transductive: it embeds unseen nodes by aggregating their neighbors, which is what makes it production-viable for fresh inventory.',
      'Sample-and-aggregate (rather than full-graph convolution) is the trick that bounds compute per node.',
    ],
  },
  {
    kind: 'template', tid: 'bst', id: 'bst', displayName: 'Behavior Sequence Transformer', org: 'Alibaba',
    paramsLabel: 'Reference graph',
    links: [
      ['Paper (Chen et al. 2019)', 'https://arxiv.org/abs/1905.06874'],
    ],
    blurb: 'Alibaba\'s CTR model that replaced sum-pooled user history with a Transformer encoder over the click sequence, with the candidate item appended as the final sequence element.',
    notes: [
      'The candidate-in-sequence trick lets self-attention compute target-aware interest weights directly.',
      'Deployed in Taobao ranking; one of the first production proofs that Transformers transfer to recsys sequences.',
    ],
  },
  {
    kind: 'template', tid: 'sli-rec', id: 'sli-rec', displayName: 'SLi-Rec', org: 'Microsoft Research / USTC',
    paramsLabel: 'Reference graph',
    links: [
      ['Paper (Yu et al. 2019, IJCAI)', 'https://www.ijcai.org/proceedings/2019/585'],
      ['GitHub (microsoft/recommenders)', 'https://github.com/recommenders-team/recommenders'],
    ],
    blurb: 'Short- and Long-term interest Recommender: a Time-aware LSTM models the evolving short-term interest while an attentive ASVD component captures stable long-term preference, fused adaptively.',
    notes: [
      'Time-aware LSTM gates take the irregular gaps between user actions as input, not just the order.',
      'The adaptive fusion learns per-user, per-moment weighting between the long- and short-term signals.',
    ],
  },
  {
    kind: 'template', tid: 'patch-tst', id: 'patch-tst', displayName: 'PatchTST', org: 'Princeton / IBM (Nie et al.)',
    paramsLabel: 'Reference graph',
    links: [
      ['Paper (Nie et al. 2023)', 'https://arxiv.org/abs/2211.14730'],
      ['GitHub', 'https://github.com/yuqinie98/PatchTST'],
    ],
    blurb: 'The Transformer that made long-horizon time-series forecasting work: each variable is sliced into patches (like ViT, but in time) and encoded channel-independently by a shared Transformer.',
    notes: [
      'Patching cuts sequence length quadratically for attention and gives each token local semantic content.',
      'Channel independence (one shared encoder applied per variable) beat channel-mixing on the standard long-horizon benchmarks.',
    ],
  },
  {
    kind: 'template', tid: 'cnn-lstm-1d', id: 'cnn-lstm-1d', displayName: '1D CNN + LSTM', org: 'Standard baseline',
    paramsLabel: 'Baseline graph',
    links: [
      ['Survey (deep learning for ECG, Hong et al. 2020)', 'https://arxiv.org/abs/2001.00254'],
    ],
    blurb: 'The standard hybrid for long 1D physiological signals (ECG, PPG, IMU): a Conv1D front-end extracts local morphology, an LSTM models long-range temporal context, a dense head classifies.',
    notes: [
      'No single canonical paper: this is the pattern that appears in hundreds of biosignal papers, included as the reference baseline.',
      'The conv stem downsamples aggressively so the LSTM sees a short, feature-rich sequence instead of raw samples.',
    ],
  },
  {
    kind: 'template', tid: 'eegnet', id: 'eegnet', displayName: 'EEGNet', org: 'US Army Research Lab (Lawhern et al.)',
    paramsLabel: '~2.6K (v4, typical config)',
    links: [
      ['Paper (Lawhern et al. 2018)', 'https://arxiv.org/abs/1611.08024'],
      ['GitHub', 'https://github.com/vlawhern/arl-eegmodels'],
    ],
    blurb: 'The compact CNN that became the universal baseline for EEG brain-computer interfaces: temporal conv, depthwise spatial conv across electrodes, separable conv, all in a few thousand parameters.',
    notes: [
      'Depthwise convolution across the electrode dimension learns spatial filters per temporal filter, mirroring classical CSP pipelines.',
      'Small enough to train on single-subject EEG datasets (hundreds of trials), which is the whole point.',
    ],
  },
  {
    kind: 'template', tid: 'eeg-conformer', id: 'eeg-conformer', displayName: 'EEG Conformer', org: 'Tsinghua (Song et al.)',
    paramsLabel: 'Reference graph',
    links: [
      ['Paper (Song et al. 2022, IEEE TNSRE)', 'https://ieeexplore.ieee.org/document/9991178'],
      ['GitHub', 'https://github.com/eeyhsong/EEG-Conformer'],
    ],
    blurb: 'Convolution meets attention for EEG decoding: an EEGNet-style conv stem tokenizes the signal, then a Transformer encoder models long-range temporal dependencies. State of the art on motor-imagery benchmarks.',
    notes: [
      'The conv stem does what patching does for ViT: turns raw 1000Hz multichannel EEG into a short token sequence the Transformer can afford.',
      'Pairs with [eegnet](../eegnet/) as the "before and after attention" story for biosignal models.',
    ],
  },
];

// ---------------------------------------------------------------------------
// Entries generated by Neurarch's paper-architecture parser
// ---------------------------------------------------------------------------

const PARSED: ParserEntry[] = [
  {
    kind: 'parser', parseName: 'ResNet-50', id: 'resnet-50', displayName: 'ResNet-50', org: 'Microsoft Research (He et al.)',
    paramsLabel: '25.6M',
    links: [
      ['Paper (He et al. 2015)', 'https://arxiv.org/abs/1512.03385'],
      ['Hugging Face', 'https://huggingface.co/microsoft/resnet-50'],
    ],
    license: 'Apache 2.0 (HF weights)',
    blurb: 'The most-cited convolutional network ever and the ILSVRC 2015 winner. This is the full 50-layer graph: conv stem, four stages of bottleneck residual blocks (3, 4, 6, 3), global average pooling, and the 1000-way head.',
    notes: [
      'Bottleneck design: 1x1 reduce, 3x3 conv, 1x1 expand in every block, which is how 50 layers stay at 25.6M parameters.',
      'Stage transitions double channels and halve resolution with strided 1x1 projections on the skip path.',
      'A decade later it is still the default vision backbone for detection, segmentation, and as a sanity-check baseline.',
    ],
  },
  {
    kind: 'parser', parseName: 'VGG-16', id: 'vgg-16', displayName: 'VGG-16', org: 'Oxford VGG (Simonyan and Zisserman)',
    paramsLabel: '138M',
    links: [
      ['Paper (Simonyan and Zisserman 2014)', 'https://arxiv.org/abs/1409.1556'],
    ],
    blurb: 'The architecture that proved depth plus uniform 3x3 convolutions beats clever filter engineering. Sixteen weight layers in five conv stages with the classic 138M-parameter dense head.',
    notes: [
      'Design rule: only 3x3 convs and 2x2 max-pools, doubling channels after each pool (64 to 512). Two stacked 3x3 convs see a 5x5 field with fewer parameters and more nonlinearity.',
      'Roughly 124M of the 138M parameters sit in the three dense layers, the inefficiency that GAP-based heads (ResNet onward) eliminated.',
      'Still everywhere as a perceptual-loss and style-transfer feature extractor.',
    ],
  },
];

// ---------------------------------------------------------------------------
// Graph builders (template-style model.json, matching public/templates/*)
// ---------------------------------------------------------------------------

interface Comp {
  id: string; type: string; name: string; scope?: string;
  position: { x: number; y: number };
  params: Record<string, unknown>;
  notes?: string;
  inputs: string[]; outputs: string[];
}
interface Conn { id: string; from: string; to: string }

function buildDecoder(s: DecoderSpec) {
  const comps: Comp[] = [];
  const conns: Conn[] = [];
  let y = 50; const X = 300; const STEP = 150; let ci = 0;
  const add = (type: string, name: string, params: Record<string, unknown>, opts: { scope?: string; notes?: string; x?: number; sameRow?: boolean } = {}) => {
    if (!opts.sameRow) y += STEP;
    const c: Comp = { id: `${type}-${comps.length + 1}`, type, name, position: { x: opts.x ?? X, y }, params, inputs: [], outputs: [] };
    if (opts.scope) c.scope = opts.scope;
    if (opts.notes) c.notes = opts.notes;
    comps.push(c);
    return c;
  };
  const wire = (from: Comp, to: Comp) => { conns.push({ id: `c${++ci}`, from: from.id, to: to.id }); };

  const seqLen = Math.min(s.ctx, 4096);
  const attnLabel = s.kvHeads < s.heads ? `GQA ${s.heads}Q:${s.kvHeads}KV` : `MHA ${s.heads} heads`;

  y -= STEP;
  const inp = add('input', 'tokens', { shape: [1, seqLen] }, { notes: `Token ids. Max context ${s.ctx.toLocaleString()} tokens; shown at ${seqLen.toLocaleString()} for shape preview.` });
  const emb = add('embedding', 'token_embed', { numEmbeddings: s.vocab, embeddingDim: s.hidden }, { scope: 'embeddings', notes: `${s.vocab.toLocaleString()}-token vocabulary, ${s.hidden}-dim embeddings.` });
  wire(inp, emb);
  const normA = add('rmsNorm', 'attn_norm', { normalizedShape: s.hidden }, { scope: 'layer.0.attention', notes: `Pre-norm RMSNorm. One of ${s.layers} identical decoder blocks is expanded below; the stack repeats x${s.layers}.` });
  wire(emb, normA);
  const attn = s.kvHeads < s.heads
    ? add('groupedQueryAttention', 'self_attn', { embedDim: s.hidden, numHeads: s.heads, numKVHeads: s.kvHeads }, { scope: 'layer.0.attention', notes: `${attnLabel}, head dim ${s.hidden / s.heads}.` })
    : add('causalAttention', 'self_attn', { embedDim: s.hidden, numHeads: s.heads }, { scope: 'layer.0.attention', notes: `${attnLabel}, head dim ${s.hidden / s.heads}, causal mask.` });
  wire(normA, attn);
  const rope = add('rope', 'rope', { dim: s.ropeDim }, { scope: 'layer.0.attention', x: X + 280, sameRow: true, notes: `Rotary position embedding, rotary dim ${s.ropeDim} per head.` });
  wire(rope, attn);
  const res1 = add('add', 'residual_1', {}, { scope: 'layer.0.attention' });
  wire(attn, res1); wire(emb, res1);
  const normF = add('rmsNorm', 'ffn_norm', { normalizedShape: s.hidden }, { scope: 'layer.0.ffn' });
  wire(res1, normF);
  const ffn = add('swiglu', 'swiglu_ffn', { embedDim: s.hidden, intermediateSize: s.ffn }, { scope: 'layer.0.ffn', notes: `SwiGLU gated FFN, intermediate size ${s.ffn.toLocaleString()} (${(s.ffn / s.hidden).toFixed(2)}x hidden).` });
  wire(normF, ffn);
  const res2 = add('add', 'residual_2', {}, { scope: 'layer.0.ffn' });
  wire(ffn, res2); wire(res1, res2);
  const normOut = add('rmsNorm', 'final_norm', { normalizedShape: s.hidden }, { scope: 'norm' });
  wire(res2, normOut);
  const head = add('linear', 'lm_head', { inFeatures: s.hidden, outFeatures: s.vocab }, { scope: 'head' });
  wire(normOut, head);
  const out = add('output', 'logits', {});
  wire(head, out);

  return {
    id: s.id,
    name: s.displayName,
    description: `${s.displayName} (${s.org}): decoder-only transformer, ${s.layers} layers x ${s.hidden} hidden, ${attnLabel}, RoPE + RMSNorm + SwiGLU. One decoder block expanded; repeats x${s.layers}. Verified against the official config.json.`,
    components: comps,
    connections: conns,
  };
}

function buildEncoder(s: EncoderSpec) {
  const comps: Comp[] = [];
  const conns: Conn[] = [];
  let y = 50; const X = 300; const STEP = 150; let ci = 0;
  const add = (type: string, name: string, params: Record<string, unknown>, opts: { scope?: string; notes?: string } = {}) => {
    const c: Comp = { id: `${type}-${comps.length + 1}`, type, name, position: { x: X, y }, params, inputs: [], outputs: [] };
    if (opts.scope) c.scope = opts.scope;
    if (opts.notes) c.notes = opts.notes;
    comps.push(c);
    y += STEP;
    return c;
  };
  const wire = (from: Comp, to: Comp) => { conns.push({ id: `c${++ci}`, from: from.id, to: to.id }); };

  const inp = add('input', 'input_ids', { shape: [1, s.maxPos] });
  const emb = add('embedding', 'word_embed', { numEmbeddings: s.vocab, embeddingDim: s.hidden }, { scope: 'embeddings', notes: `${s.vocab.toLocaleString()}-token vocabulary.` });
  wire(inp, emb);
  const pos = add('positionalEncoding', 'pos_embed', { maxLen: s.maxPos, embedDim: s.hidden }, { scope: 'embeddings', notes: `Absolute learned position embeddings, max ${s.maxPos} positions.` });
  wire(emb, pos);
  const eNorm = add('layerNorm', 'embed_norm', { normalizedShape: s.hidden }, { scope: 'embeddings' });
  wire(pos, eNorm);
  const drop = add('dropout', 'embed_drop', { p: 0.1 }, { scope: 'embeddings' });
  wire(eNorm, drop);
  const attn = add('multiHeadAttention', 'self_attn', { embedDim: s.hidden, numHeads: s.heads }, { scope: 'layer.0.attention', notes: `Bidirectional self-attention, ${s.heads} heads. One of ${s.layers} identical encoder blocks is expanded; the stack repeats x${s.layers}.` });
  wire(drop, attn);
  const res1 = add('add', 'residual_1', {}, { scope: 'layer.0.attention' });
  wire(attn, res1); wire(drop, res1);
  const n1 = add('layerNorm', 'attn_norm', { normalizedShape: s.hidden }, { scope: 'layer.0.attention', notes: 'Post-norm: LayerNorm applied after the residual add (original BERT placement).' });
  wire(res1, n1);
  const ffn = add('feedForward', 'ffn', { embedDim: s.hidden, ffDim: s.ffn }, { scope: 'layer.0.ffn', notes: `Dense FFN ${s.hidden} -> ${s.ffn} -> ${s.hidden}, GeLU activation.` });
  wire(n1, ffn);
  const res2 = add('add', 'residual_2', {}, { scope: 'layer.0.ffn' });
  wire(ffn, res2); wire(n1, res2);
  const n2 = add('layerNorm', 'ffn_norm', { normalizedShape: s.hidden }, { scope: 'layer.0.ffn' });
  wire(res2, n2);
  const out = add('output', 'hidden_states', {}, { notes: 'Sequence of contextual embeddings; [CLS] position is used for classification heads.' });
  wire(n2, out);

  return {
    id: s.id,
    name: s.displayName,
    description: `${s.displayName} (${s.org}): BERT-style bidirectional encoder, ${s.layers} layers x ${s.hidden} hidden, ${s.heads} heads, post-LayerNorm, GeLU FFN. One encoder block expanded; repeats x${s.layers}. Verified against the official config.json.`,
    components: comps,
    connections: conns,
  };
}

// ---------------------------------------------------------------------------
// README rendering
// ---------------------------------------------------------------------------

const RAW_BASE = 'https://raw.githubusercontent.com/neurarch-ai/neurarch-model-zoo/main/architectures';
const openUrl = (id: string) => `https://www.neurarch.com/?import=${RAW_BASE}/${id}/model.json`;

function specArchTable(s: DecoderSpec | EncoderSpec): string {
  const rows: Array<[string, string]> = s.kind === 'decoder'
    ? [
        ['Type', 'Decoder-only transformer (causal LM)'],
        ['Parameters', s.paramsLabel],
        ['Layers', String(s.layers)],
        ['Hidden size', String(s.hidden)],
        ['Attention', s.kvHeads < s.heads ? `Grouped-query: ${s.heads} query heads, ${s.kvHeads} KV heads` : `Multi-head: ${s.heads} heads`],
        ['Head dim', String(s.hidden / s.heads)],
        ['FFN', `SwiGLU, intermediate size ${s.ffn.toLocaleString()}`],
        ['Normalization', 'RMSNorm, pre-norm'],
        ['Positions', `RoPE (rotary dim ${s.ropeDim})`],
        ['Vocabulary', s.vocab.toLocaleString()],
        ['Max context', s.ctx.toLocaleString()],
      ]
    : [
        ['Type', 'Bidirectional encoder (BERT family)'],
        ['Parameters', s.paramsLabel],
        ['Layers', String(s.layers)],
        ['Hidden size', String(s.hidden)],
        ['Attention', `Multi-head: ${s.heads} heads`],
        ['FFN', `Dense, ${s.ffn.toLocaleString()}, GeLU`],
        ['Normalization', 'LayerNorm, post-norm'],
        ['Positions', `Absolute learned, max ${s.maxPos.toLocaleString()}`],
        ['Vocabulary', s.vocab.toLocaleString()],
      ];
  return ['| Hyperparameter | Value |', '|---|---|', ...rows.map(([k, v]) => `| ${k} | ${v} |`)].join('\n');
}

function layerTable(model: { components: Array<{ name: string; type: string; params: Record<string, unknown> }> }): string {
  const compact = (p: Record<string, unknown>) => {
    const body = Object.entries(p).map(([k, v]) => `${k}: ${Array.isArray(v) ? `[${v.join(', ')}]` : String(v)}`).join(', ');
    return body || ' ';
  };
  return [
    '| # | Layer | Type | Params |',
    '|---|---|---|---|',
    ...model.components.map((c, i) => `| ${i + 1} | ${c.name} | \`${c.type}\` | ${compact(c.params)} |`),
  ].join('\n');
}

function filesSection(): string {
  return `## Files

| File | What it is |
|---|---|
| [\`model.json\`](model.json) | The Neurarch graph. Shape-validated; open it at [neurarch.com](https://www.neurarch.com/) to edit or export training code. |
| [\`assets/diagram.svg\`](assets/diagram.svg) | Vector diagram (papers, slides). |
| [\`assets/diagram.png\`](assets/diagram.png) | Raster diagram (renders everywhere). |`;
}

function renderSpecReadme(s: DecoderSpec | EncoderSpec): string {
  const blocks = s.kind === 'decoder' ? `${s.layers} identical decoder blocks` : `${s.layers} identical encoder blocks`;
  return `# ${s.displayName}

${s.blurb}

## Model URLs

| Where | URL |
|---|---|
| **Open in Neurarch** (live, editable graph) | ${openUrl(s.id)} |
| Hugging Face | ${s.hf} |
| GitHub | ${s.github} |

## Architecture

![${s.displayName} architecture](assets/diagram.svg)

${specArchTable(s)}

The diagram and \`model.json\` show the full forward path with one of the ${blocks} expanded (the stack repeats x${s.layers}). All hyperparameters are taken from the official \`config.json\` on Hugging Face.

## Design notes

${s.notes.map((n) => `- ${n}`).join('\n')}

${filesSection()}

**License:** ${s.license}. The graph and diagrams here describe the architecture; the model weights remain under the upstream license.
`;
}

function renderEntryReadme(
  e: TemplateEntry | ParserEntry,
  model: { components: Array<{ name: string; type: string; params: Record<string, unknown> }> },
): string {
  const provenance = e.kind === 'template'
    ? 'This graph ships in Neurarch\'s in-app template library; the copy here passes shape propagation with zero errors.'
    : 'This graph is generated by Neurarch\'s architecture parser and passes shape propagation with zero errors.';
  const links = [
    ['**Open in Neurarch** (live, editable graph)', openUrl(e.id)] as Link,
    ...e.links,
  ];
  return `# ${e.displayName}

${e.blurb}

## Model URLs

| Where | URL |
|---|---|
${links.map(([l, u]) => `| ${l} | ${u} |`).join('\n')}

## Architecture

![${e.displayName} architecture](assets/diagram.svg)

<details>
<summary><b>Layer-by-layer (${model.components.length} nodes)</b></summary>

${layerTable(model)}

</details>

${provenance}

## Design notes

${e.notes.map((n) => `- ${n}`).join('\n')}

${filesSection()}
${e.license ? `\n**License:** ${e.license}. The graph and diagrams here describe the architecture; any referenced weights remain under the upstream license.\n` : ''}`;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function wireAndValidate(model: { id: string; components: Comp[]; connections: Conn[] }): number {
  for (const c of model.components) { c.inputs = []; c.outputs = []; }
  const byId = new Map(model.components.map((c) => [c.id, c]));
  for (const conn of model.connections) {
    byId.get(conn.from)!.outputs.push(conn.to);
    byId.get(conn.to)!.inputs.push(conn.from);
  }
  const result = propagateShapes(model as never);
  const errors = (result.issues ?? []).filter((i: { severity: string }) => i.severity === 'error');
  if (errors.length) {
    console.error(`✗ ${model.id}: shape errors`, errors);
    throw new Error(`shape errors in ${model.id}`);
  }
  return (result.issues ?? []).length;
}

function writeEntry(id: string, model: object, readme: string) {
  const dir = path.join(ZOO, 'architectures', id);
  fs.mkdirSync(path.join(dir, 'assets'), { recursive: true });
  fs.writeFileSync(path.join(dir, 'model.json'), JSON.stringify(model, null, 2) + '\n');
  fs.writeFileSync(path.join(dir, 'assets', 'diagram.svg'), exportPaperSvg(model as never, { attribution: true }));
  fs.writeFileSync(path.join(dir, 'README.md'), readme);
}

const ALL: Spec[] = [...DECODERS, ...ENCODERS, ...TEMPLATES, ...PARSED];
let count = 0;
for (const s of ALL) {
  if (s.kind === 'decoder' || s.kind === 'encoder') {
    const model = s.kind === 'decoder' ? buildDecoder(s) : buildEncoder(s);
    const warnings = wireAndValidate(model);
    writeEntry(s.id, model, renderSpecReadme(s));
    console.log(`✓ ${s.id} [${s.kind}] (${model.components.length} components, ${warnings} warnings)`);
  } else if (s.kind === 'template') {
    const src = path.join(NEURARCH, 'public/templates', s.tid, 'model.json');
    const model = JSON.parse(fs.readFileSync(src, 'utf8'));
    model.id = s.id;
    s.patch?.(model);
    const warnings = wireAndValidate(model);
    writeEntry(s.id, model, renderEntryReadme(s, model));
    console.log(`✓ ${s.id} [template] (${model.components.length} components, ${warnings} warnings)`);
  } else {
    const r = parsePaperTextToModel(s.parseName);
    if (!r.model) throw new Error(`parser returned no model for ${s.parseName}`);
    const model = {
      id: s.id, name: s.displayName,
      description: `${s.displayName} (${s.org}). Generated by Neurarch's architecture parser; shape-validated end to end.`,
      components: r.model.components, connections: r.model.connections,
    };
    const warnings = wireAndValidate(model as never);
    writeEntry(s.id, model, renderEntryReadme(s, model as never));
    console.log(`✓ ${s.id} [parser] (${model.components.length} components, ${warnings} warnings)`);
  }
  count++;
}
console.log(`\nDone: ${count} entries. Convert SVGs to PNG separately (resvg), then update the top-level catalog.`);
